name: GA4 to Google Sheets

on:
  workflow_dispatch:

  schedule:
    - cron: "0 4 * * *"

jobs:
  ga4-to-sheets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run GA4 script
        env:
          GA4_SERVICE_ACCOUNT_JSON: ${{ secrets.GA4_SERVICE_ACCOUNT_JSON }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

          START_DATE: ${{ vars.START_DATE || '7daysAgo' }}
          END_DATE: ${{ vars.END_DATE || 'today' }}
          RETENTION_DAYS: ${{ vars.RETENTION_DAYS || '7' }}

          APPS_CONFIG_SHEET: Apps Config
          MERGED_SHEET: GA4 Merged Data

          NOTIFICATION_EVENT_NAMES: ${{ vars.NOTIFICATION_EVENT_NAMES || 'notification_receive,notification_foreground,notification_open,notification_dismiss' }}
          KEY_EVENT_NAMES: ${{ vars.KEY_EVENT_NAMES || 'ad_impression,in_app_purchase,purchase,begin_checkout,subscribe,trial_start' }}

          FETCH_PACKAGE_NAME: ${{ vars.FETCH_PACKAGE_NAME || 'true' }}
          CLEANUP_OLD_TABS: ${{ vars.CLEANUP_OLD_TABS || 'true' }}
          GA4_ADMIN_API_BASE: ${{ vars.GA4_ADMIN_API_BASE || 'https://analyticsadmin.googleapis.com/v1beta' }}

          DEFAULT_HOME_SCREEN_NAME: MainActivity
          DEFAULT_SCREEN_FIELD: unifiedPagePathScreen
          TIMEZONE: Asia/Karachi

        run: python ga4_to_sheets.py
